/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobId = IDL.Text;
export const WorkerId = IDL.Nat;
export const AssignWorkersInput = IDL.Record({
  'jobId' : JobId,
  'assistWorkerIds' : IDL.Vec(WorkerId),
  'primaryWorkerId' : WorkerId,
});
export const Timestamp = IDL.Int;
export const ReassignmentEntry = IDL.Record({
  'changedBy' : IDL.Principal,
  'toWorkerId' : WorkerId,
  'timestamp' : Timestamp,
  'fromWorkerId' : WorkerId,
  'reason' : IDL.Text,
});
export const Assignment = IDL.Record({
  'assignedAt' : Timestamp,
  'assignedBy' : IDL.Principal,
  'reassignmentHistory' : IDL.Vec(ReassignmentEntry),
  'jobId' : JobId,
  'assistWorkerIds' : IDL.Vec(WorkerId),
  'primaryWorkerId' : WorkerId,
});
export const BulkUpsertProductInput = IDL.Record({
  'code' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const JobStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'pendingAssignment' : IDL.Null,
  'inProgress' : IDL.Null,
  'paused' : IDL.Null,
});
export const ChangeJobStatusInput = IDL.Record({
  'note' : IDL.Text,
  'jobId' : JobId,
  'newStatus' : JobStatus,
});
export const JobComplexity = IDL.Nat;
export const ProductId = IDL.Nat;
export const JobStatusEntry = IDL.Record({
  'status' : JobStatus,
  'changedBy' : IDL.Principal,
  'note' : IDL.Text,
  'timestamp' : Timestamp,
});
export const JobPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Job = IDL.Record({
  'customerName' : IDL.Text,
  'complexity' : JobComplexity,
  'status' : JobStatus,
  'carModel' : IDL.Text,
  'customerPhone' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'cancellationReason' : IDL.Opt(IDL.Text),
  'projectPrice' : IDL.Nat,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'jobId' : JobId,
  'description' : IDL.Text,
  'statusHistory' : IDL.Vec(JobStatusEntry),
  'estimatedHours' : IDL.Nat,
  'carMake' : IDL.Text,
  'priority' : JobPriority,
  'carYear' : IDL.Nat,
  'carPlate' : IDL.Text,
});
export const CreateJobInput = IDL.Record({
  'customerName' : IDL.Text,
  'complexity' : JobComplexity,
  'carModel' : IDL.Text,
  'customerPhone' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'projectPrice' : IDL.Nat,
  'description' : IDL.Text,
  'estimatedHours' : IDL.Nat,
  'carMake' : IDL.Text,
  'priority' : JobPriority,
  'carYear' : IDL.Nat,
  'carPlate' : IDL.Text,
});
export const IncentiveStatus = IDL.Variant({
  'distributed' : IDL.Null,
  'pending' : IDL.Null,
});
export const AssistShare = IDL.Record({
  'workerId' : WorkerId,
  'amount' : IDL.Nat,
});
export const IncentivePoolView = IDL.Record({
  'status' : IncentiveStatus,
  'jobId' : JobId,
  'distributedAt' : IDL.Opt(Timestamp),
  'totalPool' : IDL.Nat,
  'primaryWorkerShare' : IDL.Nat,
  'earlyBonus' : IDL.Nat,
  'assistWorkerShares' : IDL.Vec(AssistShare),
});
export const NotificationTrigger = IDL.Variant({
  'status_changed' : IDL.Null,
  'worker_idle' : IDL.Null,
  'attendance_anomaly' : IDL.Null,
  'job_completed' : IDL.Null,
  'overdue' : IDL.Null,
  'job_created' : IDL.Null,
  'incentive_awarded' : IDL.Null,
});
export const RecipientRole = IDL.Variant({
  'all' : IDL.Null,
  'admin' : IDL.Null,
  'salesManager' : IDL.Null,
  'workshopManager' : IDL.Null,
});
export const CreateNotificationInput = IDL.Record({
  'title' : IDL.Text,
  'trigger' : NotificationTrigger,
  'entityId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'recipientRole' : RecipientRole,
});
export const NotificationId = IDL.Nat;
export const CreateProductInput = IDL.Record({
  'code' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'active' : IDL.Bool,
  'code' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const CreateWorkerInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'biometricEmployeeId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const WorkerStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Worker = IDL.Record({
  'id' : WorkerId,
  'status' : WorkerStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'deactivatedAt' : IDL.Opt(Timestamp),
  'email' : IDL.Text,
  'biometricEmployeeId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const WorkerTimeEntry = IDL.Record({
  'workerId' : WorkerId,
  'trackedNanos' : IDL.Nat,
});
export const IncentiveLedgerEntry = IDL.Record({
  'workerId' : WorkerId,
  'jobId' : JobId,
  'distributedAt' : Timestamp,
  'earlyBonus' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const TimerState = IDL.Variant({
  'stopped' : IDL.Null,
  'running' : IDL.Null,
  'paused' : IDL.Null,
});
export const TimerRecordView = IDL.Record({
  'totalPausedNanos' : IDL.Nat,
  'pausedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'jobId' : JobId,
  'state' : TimerState,
  'elapsedSeconds' : IDL.Nat,
});
export const AttendanceSummary = IDL.Record({
  'month' : IDL.Text,
  'workerId' : WorkerId,
  'daysAbsent' : IDL.Nat,
  'daysPresent' : IDL.Nat,
  'daysLate' : IDL.Nat,
});
export const NotificationRecord = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'trigger' : NotificationTrigger,
  'createdAt' : Timestamp,
  'entityId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'recipientRole' : RecipientRole,
  'readBy' : IDL.Vec(IDL.Principal),
});
export const AppSettings = IDL.Record({
  'overdueAlertOffsetHours' : IDL.Nat,
  'earlyBonusThresholdPercent' : IDL.Nat,
  'incentivePoolPercent' : IDL.Nat,
  'absentFlagDays' : IDL.Nat,
  'idleDetectionMinutes' : IDL.Nat,
  'lateThresholdMinutes' : IDL.Nat,
});
export const TemplateId = IDL.Nat;
export const NotificationTemplate = IDL.Record({
  'id' : TemplateId,
  'messageTemplate' : IDL.Text,
  'active' : IDL.Bool,
  'trigger' : NotificationTrigger,
  'updatedAt' : Timestamp,
  'updatedBy' : IDL.Principal,
  'titleTemplate' : IDL.Text,
});
export const BiometricEvent = IDL.Variant({
  'checkIn' : IDL.Null,
  'checkOut' : IDL.Null,
});
export const BiometricRawRecord = IDL.Record({
  'biometricEmployeeId' : IDL.Text,
  'event' : BiometricEvent,
  'eventTimestamp' : Timestamp,
});
export const ImportBatchId = IDL.Text;
export const ImportAttendanceInput = IDL.Record({
  'records' : IDL.Vec(BiometricRawRecord),
  'batchId' : ImportBatchId,
});
export const AttendanceFilter = IDL.Record({
  'workerId' : IDL.Opt(WorkerId),
  'isLate' : IDL.Opt(IDL.Bool),
  'toDate' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Text),
  'isAbsent' : IDL.Opt(IDL.Bool),
});
export const AttendanceId = IDL.Nat;
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'checkOutAt' : IDL.Opt(Timestamp),
  'importedAt' : Timestamp,
  'isLate' : IDL.Bool,
  'biometricEmployeeId' : IDL.Text,
  'checkInAt' : IDL.Opt(Timestamp),
  'importBatchId' : ImportBatchId,
  'isAbsent' : IDL.Bool,
});
export const AuditEntityType = IDL.Variant({
  'job' : IDL.Null,
  'setting' : IDL.Null,
  'assignment' : IDL.Null,
  'incentive' : IDL.Null,
  'notification' : IDL.Null,
  'attendance' : IDL.Null,
  'worker' : IDL.Null,
  'product' : IDL.Null,
});
export const AuditQueryFilter = IDL.Record({
  'toTime' : IDL.Opt(Timestamp),
  'entityId' : IDL.Opt(IDL.Text),
  'fromTime' : IDL.Opt(Timestamp),
  'actorPrincipal' : IDL.Opt(IDL.Principal),
  'entityType' : IDL.Opt(AuditEntityType),
});
export const AuditEntryId = IDL.Nat;
export const AuditEntry = IDL.Record({
  'id' : AuditEntryId,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
  'entityType' : AuditEntityType,
});
export const ReassignWorkerInput = IDL.Record({
  'jobId' : JobId,
  'toWorkerId' : WorkerId,
  'fromWorkerId' : WorkerId,
  'reason' : IDL.Text,
});
export const UpdateJobInput = IDL.Record({
  'customerName' : IDL.Text,
  'complexity' : JobComplexity,
  'carModel' : IDL.Text,
  'customerPhone' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'projectPrice' : IDL.Nat,
  'jobId' : JobId,
  'description' : IDL.Text,
  'estimatedHours' : IDL.Nat,
  'carMake' : IDL.Text,
  'priority' : JobPriority,
  'carYear' : IDL.Nat,
  'carPlate' : IDL.Text,
});
export const UpdateSettingsInput = IDL.Record({
  'overdueAlertOffsetHours' : IDL.Opt(IDL.Nat),
  'earlyBonusThresholdPercent' : IDL.Opt(IDL.Nat),
  'incentivePoolPercent' : IDL.Opt(IDL.Nat),
  'absentFlagDays' : IDL.Opt(IDL.Nat),
  'idleDetectionMinutes' : IDL.Opt(IDL.Nat),
  'lateThresholdMinutes' : IDL.Opt(IDL.Nat),
});
export const UpdateWorkerInput = IDL.Record({
  'id' : WorkerId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'biometricEmployeeId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const UpsertTemplateInput = IDL.Record({
  'messageTemplate' : IDL.Text,
  'active' : IDL.Bool,
  'trigger' : NotificationTrigger,
  'titleTemplate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignWorkers' : IDL.Func([AssignWorkersInput], [Assignment], []),
  'bulkUpsertProducts' : IDL.Func(
      [IDL.Vec(BulkUpsertProductInput)],
      [IDL.Nat],
      [],
    ),
  'changeJobStatus' : IDL.Func([ChangeJobStatusInput], [IDL.Opt(Job)], []),
  'createJob' : IDL.Func([CreateJobInput], [Job], []),
  'createJobIncentivePool' : IDL.Func(
      [JobId, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Opt(IncentivePoolView)],
      [],
    ),
  'createNotification' : IDL.Func(
      [CreateNotificationInput],
      [NotificationId],
      [],
    ),
  'createProduct' : IDL.Func([CreateProductInput], [Product], []),
  'createWorker' : IDL.Func([CreateWorkerInput], [Worker], []),
  'deactivateProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deactivateWorker' : IDL.Func([WorkerId], [IDL.Bool], []),
  'distributeJobIncentive' : IDL.Func(
      [JobId, WorkerId, IDL.Vec(WorkerTimeEntry), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'getAllIncentiveLedger' : IDL.Func(
      [],
      [IDL.Vec(IncentiveLedgerEntry)],
      ['query'],
    ),
  'getAssignment' : IDL.Func([JobId], [IDL.Opt(Assignment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIdleJobs' : IDL.Func([], [IDL.Vec(JobId)], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getJobIncentivePool' : IDL.Func(
      [JobId],
      [IDL.Opt(IncentivePoolView)],
      ['query'],
    ),
  'getJobTimerState' : IDL.Func([JobId], [IDL.Opt(TimerRecordView)], ['query']),
  'getMonthlyAttendanceSummary' : IDL.Func(
      [WorkerId, IDL.Text],
      [AttendanceSummary],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func(
      [RecipientRole],
      [IDL.Vec(NotificationRecord)],
      ['query'],
    ),
  'getPendingIncentives' : IDL.Func(
      [],
      [IDL.Vec(IncentivePoolView)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getTemplateForTrigger' : IDL.Func(
      [NotificationTrigger],
      [IDL.Opt(NotificationTemplate)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([RecipientRole], [IDL.Nat], ['query']),
  'getWorker' : IDL.Func([WorkerId], [IDL.Opt(Worker)], ['query']),
  'getWorkerLedger' : IDL.Func(
      [WorkerId],
      [IDL.Vec(IncentiveLedgerEntry)],
      ['query'],
    ),
  'importAttendance' : IDL.Func([ImportAttendanceInput], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isJobOverdue' : IDL.Func([JobId], [IDL.Opt(IDL.Bool)], ['query']),
  'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listBiometricMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, WorkerId))],
      ['query'],
    ),
  'listJobsByStatus' : IDL.Func([JobStatus], [IDL.Vec(Job)], ['query']),
  'listJobsByWorker' : IDL.Func([WorkerId], [IDL.Vec(Job)], ['query']),
  'listNotificationTemplates' : IDL.Func(
      [],
      [IDL.Vec(NotificationTemplate)],
      ['query'],
    ),
  'listWorkers' : IDL.Func(
      [IDL.Opt(WorkerStatus)],
      [IDL.Vec(Worker)],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([RecipientRole], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'pauseJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
  'queryAttendance' : IDL.Func(
      [AttendanceFilter],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'queryAuditLog' : IDL.Func(
      [AuditQueryFilter],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'reassignAssistWorker' : IDL.Func(
      [ReassignWorkerInput],
      [IDL.Opt(Assignment)],
      [],
    ),
  'reassignPrimaryWorker' : IDL.Func(
      [ReassignWorkerInput],
      [IDL.Opt(Assignment)],
      [],
    ),
  'resumeJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
  'setBiometricMapping' : IDL.Func([IDL.Text, WorkerId], [], []),
  'setIdleThresholdMinutes' : IDL.Func([IDL.Nat], [], []),
  'setPoolPercent' : IDL.Func([IDL.Nat], [], []),
  'startJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
  'stopJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
  'updateJob' : IDL.Func([UpdateJobInput], [IDL.Opt(Job)], []),
  'updateSettings' : IDL.Func([UpdateSettingsInput], [AppSettings], []),
  'updateWorker' : IDL.Func([UpdateWorkerInput], [IDL.Opt(Worker)], []),
  'upsertNotificationTemplate' : IDL.Func(
      [UpsertTemplateInput],
      [TemplateId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobId = IDL.Text;
  const WorkerId = IDL.Nat;
  const AssignWorkersInput = IDL.Record({
    'jobId' : JobId,
    'assistWorkerIds' : IDL.Vec(WorkerId),
    'primaryWorkerId' : WorkerId,
  });
  const Timestamp = IDL.Int;
  const ReassignmentEntry = IDL.Record({
    'changedBy' : IDL.Principal,
    'toWorkerId' : WorkerId,
    'timestamp' : Timestamp,
    'fromWorkerId' : WorkerId,
    'reason' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'assignedAt' : Timestamp,
    'assignedBy' : IDL.Principal,
    'reassignmentHistory' : IDL.Vec(ReassignmentEntry),
    'jobId' : JobId,
    'assistWorkerIds' : IDL.Vec(WorkerId),
    'primaryWorkerId' : WorkerId,
  });
  const BulkUpsertProductInput = IDL.Record({
    'code' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const JobStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'pendingAssignment' : IDL.Null,
    'inProgress' : IDL.Null,
    'paused' : IDL.Null,
  });
  const ChangeJobStatusInput = IDL.Record({
    'note' : IDL.Text,
    'jobId' : JobId,
    'newStatus' : JobStatus,
  });
  const JobComplexity = IDL.Nat;
  const ProductId = IDL.Nat;
  const JobStatusEntry = IDL.Record({
    'status' : JobStatus,
    'changedBy' : IDL.Principal,
    'note' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const JobPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Job = IDL.Record({
    'customerName' : IDL.Text,
    'complexity' : JobComplexity,
    'status' : JobStatus,
    'carModel' : IDL.Text,
    'customerPhone' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'cancellationReason' : IDL.Opt(IDL.Text),
    'projectPrice' : IDL.Nat,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'jobId' : JobId,
    'description' : IDL.Text,
    'statusHistory' : IDL.Vec(JobStatusEntry),
    'estimatedHours' : IDL.Nat,
    'carMake' : IDL.Text,
    'priority' : JobPriority,
    'carYear' : IDL.Nat,
    'carPlate' : IDL.Text,
  });
  const CreateJobInput = IDL.Record({
    'customerName' : IDL.Text,
    'complexity' : JobComplexity,
    'carModel' : IDL.Text,
    'customerPhone' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'projectPrice' : IDL.Nat,
    'description' : IDL.Text,
    'estimatedHours' : IDL.Nat,
    'carMake' : IDL.Text,
    'priority' : JobPriority,
    'carYear' : IDL.Nat,
    'carPlate' : IDL.Text,
  });
  const IncentiveStatus = IDL.Variant({
    'distributed' : IDL.Null,
    'pending' : IDL.Null,
  });
  const AssistShare = IDL.Record({ 'workerId' : WorkerId, 'amount' : IDL.Nat });
  const IncentivePoolView = IDL.Record({
    'status' : IncentiveStatus,
    'jobId' : JobId,
    'distributedAt' : IDL.Opt(Timestamp),
    'totalPool' : IDL.Nat,
    'primaryWorkerShare' : IDL.Nat,
    'earlyBonus' : IDL.Nat,
    'assistWorkerShares' : IDL.Vec(AssistShare),
  });
  const NotificationTrigger = IDL.Variant({
    'status_changed' : IDL.Null,
    'worker_idle' : IDL.Null,
    'attendance_anomaly' : IDL.Null,
    'job_completed' : IDL.Null,
    'overdue' : IDL.Null,
    'job_created' : IDL.Null,
    'incentive_awarded' : IDL.Null,
  });
  const RecipientRole = IDL.Variant({
    'all' : IDL.Null,
    'admin' : IDL.Null,
    'salesManager' : IDL.Null,
    'workshopManager' : IDL.Null,
  });
  const CreateNotificationInput = IDL.Record({
    'title' : IDL.Text,
    'trigger' : NotificationTrigger,
    'entityId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'recipientRole' : RecipientRole,
  });
  const NotificationId = IDL.Nat;
  const CreateProductInput = IDL.Record({
    'code' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'active' : IDL.Bool,
    'code' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const CreateWorkerInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'biometricEmployeeId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const WorkerStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Worker = IDL.Record({
    'id' : WorkerId,
    'status' : WorkerStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'deactivatedAt' : IDL.Opt(Timestamp),
    'email' : IDL.Text,
    'biometricEmployeeId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const WorkerTimeEntry = IDL.Record({
    'workerId' : WorkerId,
    'trackedNanos' : IDL.Nat,
  });
  const IncentiveLedgerEntry = IDL.Record({
    'workerId' : WorkerId,
    'jobId' : JobId,
    'distributedAt' : Timestamp,
    'earlyBonus' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const TimerState = IDL.Variant({
    'stopped' : IDL.Null,
    'running' : IDL.Null,
    'paused' : IDL.Null,
  });
  const TimerRecordView = IDL.Record({
    'totalPausedNanos' : IDL.Nat,
    'pausedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'jobId' : JobId,
    'state' : TimerState,
    'elapsedSeconds' : IDL.Nat,
  });
  const AttendanceSummary = IDL.Record({
    'month' : IDL.Text,
    'workerId' : WorkerId,
    'daysAbsent' : IDL.Nat,
    'daysPresent' : IDL.Nat,
    'daysLate' : IDL.Nat,
  });
  const NotificationRecord = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'trigger' : NotificationTrigger,
    'createdAt' : Timestamp,
    'entityId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'recipientRole' : RecipientRole,
    'readBy' : IDL.Vec(IDL.Principal),
  });
  const AppSettings = IDL.Record({
    'overdueAlertOffsetHours' : IDL.Nat,
    'earlyBonusThresholdPercent' : IDL.Nat,
    'incentivePoolPercent' : IDL.Nat,
    'absentFlagDays' : IDL.Nat,
    'idleDetectionMinutes' : IDL.Nat,
    'lateThresholdMinutes' : IDL.Nat,
  });
  const TemplateId = IDL.Nat;
  const NotificationTemplate = IDL.Record({
    'id' : TemplateId,
    'messageTemplate' : IDL.Text,
    'active' : IDL.Bool,
    'trigger' : NotificationTrigger,
    'updatedAt' : Timestamp,
    'updatedBy' : IDL.Principal,
    'titleTemplate' : IDL.Text,
  });
  const BiometricEvent = IDL.Variant({
    'checkIn' : IDL.Null,
    'checkOut' : IDL.Null,
  });
  const BiometricRawRecord = IDL.Record({
    'biometricEmployeeId' : IDL.Text,
    'event' : BiometricEvent,
    'eventTimestamp' : Timestamp,
  });
  const ImportBatchId = IDL.Text;
  const ImportAttendanceInput = IDL.Record({
    'records' : IDL.Vec(BiometricRawRecord),
    'batchId' : ImportBatchId,
  });
  const AttendanceFilter = IDL.Record({
    'workerId' : IDL.Opt(WorkerId),
    'isLate' : IDL.Opt(IDL.Bool),
    'toDate' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Text),
    'isAbsent' : IDL.Opt(IDL.Bool),
  });
  const AttendanceId = IDL.Nat;
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'checkOutAt' : IDL.Opt(Timestamp),
    'importedAt' : Timestamp,
    'isLate' : IDL.Bool,
    'biometricEmployeeId' : IDL.Text,
    'checkInAt' : IDL.Opt(Timestamp),
    'importBatchId' : ImportBatchId,
    'isAbsent' : IDL.Bool,
  });
  const AuditEntityType = IDL.Variant({
    'job' : IDL.Null,
    'setting' : IDL.Null,
    'assignment' : IDL.Null,
    'incentive' : IDL.Null,
    'notification' : IDL.Null,
    'attendance' : IDL.Null,
    'worker' : IDL.Null,
    'product' : IDL.Null,
  });
  const AuditQueryFilter = IDL.Record({
    'toTime' : IDL.Opt(Timestamp),
    'entityId' : IDL.Opt(IDL.Text),
    'fromTime' : IDL.Opt(Timestamp),
    'actorPrincipal' : IDL.Opt(IDL.Principal),
    'entityType' : IDL.Opt(AuditEntityType),
  });
  const AuditEntryId = IDL.Nat;
  const AuditEntry = IDL.Record({
    'id' : AuditEntryId,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
    'entityType' : AuditEntityType,
  });
  const ReassignWorkerInput = IDL.Record({
    'jobId' : JobId,
    'toWorkerId' : WorkerId,
    'fromWorkerId' : WorkerId,
    'reason' : IDL.Text,
  });
  const UpdateJobInput = IDL.Record({
    'customerName' : IDL.Text,
    'complexity' : JobComplexity,
    'carModel' : IDL.Text,
    'customerPhone' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'projectPrice' : IDL.Nat,
    'jobId' : JobId,
    'description' : IDL.Text,
    'estimatedHours' : IDL.Nat,
    'carMake' : IDL.Text,
    'priority' : JobPriority,
    'carYear' : IDL.Nat,
    'carPlate' : IDL.Text,
  });
  const UpdateSettingsInput = IDL.Record({
    'overdueAlertOffsetHours' : IDL.Opt(IDL.Nat),
    'earlyBonusThresholdPercent' : IDL.Opt(IDL.Nat),
    'incentivePoolPercent' : IDL.Opt(IDL.Nat),
    'absentFlagDays' : IDL.Opt(IDL.Nat),
    'idleDetectionMinutes' : IDL.Opt(IDL.Nat),
    'lateThresholdMinutes' : IDL.Opt(IDL.Nat),
  });
  const UpdateWorkerInput = IDL.Record({
    'id' : WorkerId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'biometricEmployeeId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const UpsertTemplateInput = IDL.Record({
    'messageTemplate' : IDL.Text,
    'active' : IDL.Bool,
    'trigger' : NotificationTrigger,
    'titleTemplate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignWorkers' : IDL.Func([AssignWorkersInput], [Assignment], []),
    'bulkUpsertProducts' : IDL.Func(
        [IDL.Vec(BulkUpsertProductInput)],
        [IDL.Nat],
        [],
      ),
    'changeJobStatus' : IDL.Func([ChangeJobStatusInput], [IDL.Opt(Job)], []),
    'createJob' : IDL.Func([CreateJobInput], [Job], []),
    'createJobIncentivePool' : IDL.Func(
        [JobId, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Opt(IncentivePoolView)],
        [],
      ),
    'createNotification' : IDL.Func(
        [CreateNotificationInput],
        [NotificationId],
        [],
      ),
    'createProduct' : IDL.Func([CreateProductInput], [Product], []),
    'createWorker' : IDL.Func([CreateWorkerInput], [Worker], []),
    'deactivateProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deactivateWorker' : IDL.Func([WorkerId], [IDL.Bool], []),
    'distributeJobIncentive' : IDL.Func(
        [JobId, WorkerId, IDL.Vec(WorkerTimeEntry), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAllIncentiveLedger' : IDL.Func(
        [],
        [IDL.Vec(IncentiveLedgerEntry)],
        ['query'],
      ),
    'getAssignment' : IDL.Func([JobId], [IDL.Opt(Assignment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIdleJobs' : IDL.Func([], [IDL.Vec(JobId)], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getJobIncentivePool' : IDL.Func(
        [JobId],
        [IDL.Opt(IncentivePoolView)],
        ['query'],
      ),
    'getJobTimerState' : IDL.Func(
        [JobId],
        [IDL.Opt(TimerRecordView)],
        ['query'],
      ),
    'getMonthlyAttendanceSummary' : IDL.Func(
        [WorkerId, IDL.Text],
        [AttendanceSummary],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [RecipientRole],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getPendingIncentives' : IDL.Func(
        [],
        [IDL.Vec(IncentivePoolView)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getTemplateForTrigger' : IDL.Func(
        [NotificationTrigger],
        [IDL.Opt(NotificationTemplate)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([RecipientRole], [IDL.Nat], ['query']),
    'getWorker' : IDL.Func([WorkerId], [IDL.Opt(Worker)], ['query']),
    'getWorkerLedger' : IDL.Func(
        [WorkerId],
        [IDL.Vec(IncentiveLedgerEntry)],
        ['query'],
      ),
    'importAttendance' : IDL.Func([ImportAttendanceInput], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isJobOverdue' : IDL.Func([JobId], [IDL.Opt(IDL.Bool)], ['query']),
    'listActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listBiometricMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, WorkerId))],
        ['query'],
      ),
    'listJobsByStatus' : IDL.Func([JobStatus], [IDL.Vec(Job)], ['query']),
    'listJobsByWorker' : IDL.Func([WorkerId], [IDL.Vec(Job)], ['query']),
    'listNotificationTemplates' : IDL.Func(
        [],
        [IDL.Vec(NotificationTemplate)],
        ['query'],
      ),
    'listWorkers' : IDL.Func(
        [IDL.Opt(WorkerStatus)],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([RecipientRole], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'pauseJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
    'queryAttendance' : IDL.Func(
        [AttendanceFilter],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'queryAuditLog' : IDL.Func(
        [AuditQueryFilter],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'reassignAssistWorker' : IDL.Func(
        [ReassignWorkerInput],
        [IDL.Opt(Assignment)],
        [],
      ),
    'reassignPrimaryWorker' : IDL.Func(
        [ReassignWorkerInput],
        [IDL.Opt(Assignment)],
        [],
      ),
    'resumeJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
    'setBiometricMapping' : IDL.Func([IDL.Text, WorkerId], [], []),
    'setIdleThresholdMinutes' : IDL.Func([IDL.Nat], [], []),
    'setPoolPercent' : IDL.Func([IDL.Nat], [], []),
    'startJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
    'stopJobTimer' : IDL.Func([JobId], [TimerRecordView], []),
    'updateJob' : IDL.Func([UpdateJobInput], [IDL.Opt(Job)], []),
    'updateSettings' : IDL.Func([UpdateSettingsInput], [AppSettings], []),
    'updateWorker' : IDL.Func([UpdateWorkerInput], [IDL.Opt(Worker)], []),
    'upsertNotificationTemplate' : IDL.Func(
        [UpsertTemplateInput],
        [TemplateId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };