/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'overdueAlertOffsetHours' : bigint,
  'earlyBonusThresholdPercent' : bigint,
  'incentivePoolPercent' : bigint,
  'absentFlagDays' : bigint,
  'idleDetectionMinutes' : bigint,
  'lateThresholdMinutes' : bigint,
}
export interface AssignWorkersInput {
  'jobId' : JobId,
  'assistWorkerIds' : Array<WorkerId>,
  'primaryWorkerId' : WorkerId,
}
export interface Assignment {
  'assignedAt' : Timestamp,
  'assignedBy' : Principal,
  'reassignmentHistory' : Array<ReassignmentEntry>,
  'jobId' : JobId,
  'assistWorkerIds' : Array<WorkerId>,
  'primaryWorkerId' : WorkerId,
}
export interface AssistShare { 'workerId' : WorkerId, 'amount' : bigint }
export interface AttendanceFilter {
  'workerId' : [] | [WorkerId],
  'isLate' : [] | [boolean],
  'toDate' : [] | [string],
  'fromDate' : [] | [string],
  'isAbsent' : [] | [boolean],
}
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'workerId' : WorkerId,
  'date' : string,
  'checkOutAt' : [] | [Timestamp],
  'importedAt' : Timestamp,
  'isLate' : boolean,
  'biometricEmployeeId' : string,
  'checkInAt' : [] | [Timestamp],
  'importBatchId' : ImportBatchId,
  'isAbsent' : boolean,
}
export interface AttendanceSummary {
  'month' : string,
  'workerId' : WorkerId,
  'daysAbsent' : bigint,
  'daysPresent' : bigint,
  'daysLate' : bigint,
}
export type AuditEntityType = { 'job' : null } |
  { 'setting' : null } |
  { 'assignment' : null } |
  { 'incentive' : null } |
  { 'notification' : null } |
  { 'attendance' : null } |
  { 'worker' : null } |
  { 'product' : null };
export interface AuditEntry {
  'id' : AuditEntryId,
  'action' : string,
  'entityId' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'actorPrincipal' : Principal,
  'entityType' : AuditEntityType,
}
export type AuditEntryId = bigint;
export interface AuditQueryFilter {
  'toTime' : [] | [Timestamp],
  'entityId' : [] | [string],
  'fromTime' : [] | [Timestamp],
  'actorPrincipal' : [] | [Principal],
  'entityType' : [] | [AuditEntityType],
}
export type BiometricEvent = { 'checkIn' : null } |
  { 'checkOut' : null };
export interface BiometricRawRecord {
  'biometricEmployeeId' : string,
  'event' : BiometricEvent,
  'eventTimestamp' : Timestamp,
}
export interface BulkUpsertProductInput {
  'code' : [] | [string],
  'name' : string,
  'notes' : [] | [string],
}
export interface ChangeJobStatusInput {
  'note' : string,
  'jobId' : JobId,
  'newStatus' : JobStatus,
}
export interface CreateJobInput {
  'customerName' : string,
  'complexity' : JobComplexity,
  'carModel' : string,
  'customerPhone' : string,
  'productIds' : Array<ProductId>,
  'projectPrice' : bigint,
  'description' : string,
  'estimatedHours' : bigint,
  'carMake' : string,
  'priority' : JobPriority,
  'carYear' : bigint,
  'carPlate' : string,
}
export interface CreateNotificationInput {
  'title' : string,
  'trigger' : NotificationTrigger,
  'entityId' : [] | [string],
  'message' : string,
  'recipientRole' : RecipientRole,
}
export interface CreateProductInput {
  'code' : [] | [string],
  'name' : string,
  'notes' : [] | [string],
}
export interface CreateWorkerInput {
  'name' : string,
  'email' : string,
  'biometricEmployeeId' : [] | [string],
  'phone' : string,
}
export interface ImportAttendanceInput {
  'records' : Array<BiometricRawRecord>,
  'batchId' : ImportBatchId,
}
export type ImportBatchId = string;
export interface IncentiveLedgerEntry {
  'workerId' : WorkerId,
  'jobId' : JobId,
  'distributedAt' : Timestamp,
  'earlyBonus' : boolean,
  'amount' : bigint,
}
export interface IncentivePoolView {
  'status' : IncentiveStatus,
  'jobId' : JobId,
  'distributedAt' : [] | [Timestamp],
  'totalPool' : bigint,
  'primaryWorkerShare' : bigint,
  'earlyBonus' : bigint,
  'assistWorkerShares' : Array<AssistShare>,
}
export type IncentiveStatus = { 'distributed' : null } |
  { 'pending' : null };
export interface Job {
  'customerName' : string,
  'complexity' : JobComplexity,
  'status' : JobStatus,
  'carModel' : string,
  'customerPhone' : string,
  'productIds' : Array<ProductId>,
  'cancellationReason' : [] | [string],
  'projectPrice' : bigint,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'jobId' : JobId,
  'description' : string,
  'statusHistory' : Array<JobStatusEntry>,
  'estimatedHours' : bigint,
  'carMake' : string,
  'priority' : JobPriority,
  'carYear' : bigint,
  'carPlate' : string,
}
export type JobComplexity = bigint;
export type JobId = string;
export type JobPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type JobStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'pendingAssignment' : null } |
  { 'inProgress' : null } |
  { 'paused' : null };
export interface JobStatusEntry {
  'status' : JobStatus,
  'changedBy' : Principal,
  'note' : string,
  'timestamp' : Timestamp,
}
export type NotificationId = bigint;
export interface NotificationRecord {
  'id' : NotificationId,
  'title' : string,
  'trigger' : NotificationTrigger,
  'createdAt' : Timestamp,
  'entityId' : [] | [string],
  'message' : string,
  'recipientRole' : RecipientRole,
  'readBy' : Array<Principal>,
}
export interface NotificationTemplate {
  'id' : TemplateId,
  'messageTemplate' : string,
  'active' : boolean,
  'trigger' : NotificationTrigger,
  'updatedAt' : Timestamp,
  'updatedBy' : Principal,
  'titleTemplate' : string,
}
export type NotificationTrigger = { 'status_changed' : null } |
  { 'worker_idle' : null } |
  { 'attendance_anomaly' : null } |
  { 'job_completed' : null } |
  { 'overdue' : null } |
  { 'job_created' : null } |
  { 'incentive_awarded' : null };
export interface Product {
  'id' : ProductId,
  'active' : boolean,
  'code' : [] | [string],
  'name' : string,
  'notes' : [] | [string],
}
export type ProductId = bigint;
export interface ReassignWorkerInput {
  'jobId' : JobId,
  'toWorkerId' : WorkerId,
  'fromWorkerId' : WorkerId,
  'reason' : string,
}
export interface ReassignmentEntry {
  'changedBy' : Principal,
  'toWorkerId' : WorkerId,
  'timestamp' : Timestamp,
  'fromWorkerId' : WorkerId,
  'reason' : string,
}
export type RecipientRole = { 'all' : null } |
  { 'admin' : null } |
  { 'salesManager' : null } |
  { 'workshopManager' : null };
export type TemplateId = bigint;
export interface TimerRecordView {
  'totalPausedNanos' : bigint,
  'pausedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'jobId' : JobId,
  'state' : TimerState,
  'elapsedSeconds' : bigint,
}
export type TimerState = { 'stopped' : null } |
  { 'running' : null } |
  { 'paused' : null };
export type Timestamp = bigint;
export interface UpdateJobInput {
  'customerName' : string,
  'complexity' : JobComplexity,
  'carModel' : string,
  'customerPhone' : string,
  'productIds' : Array<ProductId>,
  'projectPrice' : bigint,
  'jobId' : JobId,
  'description' : string,
  'estimatedHours' : bigint,
  'carMake' : string,
  'priority' : JobPriority,
  'carYear' : bigint,
  'carPlate' : string,
}
export interface UpdateSettingsInput {
  'overdueAlertOffsetHours' : [] | [bigint],
  'earlyBonusThresholdPercent' : [] | [bigint],
  'incentivePoolPercent' : [] | [bigint],
  'absentFlagDays' : [] | [bigint],
  'idleDetectionMinutes' : [] | [bigint],
  'lateThresholdMinutes' : [] | [bigint],
}
export interface UpdateWorkerInput {
  'id' : WorkerId,
  'name' : string,
  'email' : string,
  'biometricEmployeeId' : [] | [string],
  'phone' : string,
}
export interface UpsertTemplateInput {
  'messageTemplate' : string,
  'active' : boolean,
  'trigger' : NotificationTrigger,
  'titleTemplate' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'id' : WorkerId,
  'status' : WorkerStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'deactivatedAt' : [] | [Timestamp],
  'email' : string,
  'biometricEmployeeId' : [] | [string],
  'phone' : string,
}
export type WorkerId = bigint;
export type WorkerStatus = { 'active' : null } |
  { 'inactive' : null };
export interface WorkerTimeEntry {
  'workerId' : WorkerId,
  'trackedNanos' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignWorkers' : ActorMethod<[AssignWorkersInput], Assignment>,
  'bulkUpsertProducts' : ActorMethod<[Array<BulkUpsertProductInput>], bigint>,
  'changeJobStatus' : ActorMethod<[ChangeJobStatusInput], [] | [Job]>,
  'createJob' : ActorMethod<[CreateJobInput], Job>,
  'createJobIncentivePool' : ActorMethod<
    [JobId, bigint, bigint, bigint],
    [] | [IncentivePoolView]
  >,
  'createNotification' : ActorMethod<[CreateNotificationInput], NotificationId>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'createWorker' : ActorMethod<[CreateWorkerInput], Worker>,
  'deactivateProduct' : ActorMethod<[ProductId], boolean>,
  'deactivateWorker' : ActorMethod<[WorkerId], boolean>,
  'distributeJobIncentive' : ActorMethod<
    [JobId, WorkerId, Array<WorkerTimeEntry>, bigint, bigint],
    undefined
  >,
  'getAllIncentiveLedger' : ActorMethod<[], Array<IncentiveLedgerEntry>>,
  'getAssignment' : ActorMethod<[JobId], [] | [Assignment]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIdleJobs' : ActorMethod<[], Array<JobId>>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getJobIncentivePool' : ActorMethod<[JobId], [] | [IncentivePoolView]>,
  'getJobTimerState' : ActorMethod<[JobId], [] | [TimerRecordView]>,
  'getMonthlyAttendanceSummary' : ActorMethod<
    [WorkerId, string],
    AttendanceSummary
  >,
  'getMyNotifications' : ActorMethod<
    [RecipientRole],
    Array<NotificationRecord>
  >,
  'getPendingIncentives' : ActorMethod<[], Array<IncentivePoolView>>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getTemplateForTrigger' : ActorMethod<
    [NotificationTrigger],
    [] | [NotificationTemplate]
  >,
  'getUnreadCount' : ActorMethod<[RecipientRole], bigint>,
  'getWorker' : ActorMethod<[WorkerId], [] | [Worker]>,
  'getWorkerLedger' : ActorMethod<[WorkerId], Array<IncentiveLedgerEntry>>,
  'importAttendance' : ActorMethod<[ImportAttendanceInput], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isJobOverdue' : ActorMethod<[JobId], [] | [boolean]>,
  'listActiveProducts' : ActorMethod<[], Array<Product>>,
  'listAllJobs' : ActorMethod<[], Array<Job>>,
  'listBiometricMappings' : ActorMethod<[], Array<[string, WorkerId]>>,
  'listJobsByStatus' : ActorMethod<[JobStatus], Array<Job>>,
  'listJobsByWorker' : ActorMethod<[WorkerId], Array<Job>>,
  'listNotificationTemplates' : ActorMethod<[], Array<NotificationTemplate>>,
  'listWorkers' : ActorMethod<[[] | [WorkerStatus]], Array<Worker>>,
  'markAllNotificationsRead' : ActorMethod<[RecipientRole], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'pauseJobTimer' : ActorMethod<[JobId], TimerRecordView>,
  'queryAttendance' : ActorMethod<[AttendanceFilter], Array<AttendanceRecord>>,
  'queryAuditLog' : ActorMethod<[AuditQueryFilter], Array<AuditEntry>>,
  'reassignAssistWorker' : ActorMethod<
    [ReassignWorkerInput],
    [] | [Assignment]
  >,
  'reassignPrimaryWorker' : ActorMethod<
    [ReassignWorkerInput],
    [] | [Assignment]
  >,
  'resumeJobTimer' : ActorMethod<[JobId], TimerRecordView>,
  'setBiometricMapping' : ActorMethod<[string, WorkerId], undefined>,
  'setIdleThresholdMinutes' : ActorMethod<[bigint], undefined>,
  'setPoolPercent' : ActorMethod<[bigint], undefined>,
  'startJobTimer' : ActorMethod<[JobId], TimerRecordView>,
  'stopJobTimer' : ActorMethod<[JobId], TimerRecordView>,
  'updateJob' : ActorMethod<[UpdateJobInput], [] | [Job]>,
  'updateSettings' : ActorMethod<[UpdateSettingsInput], AppSettings>,
  'updateWorker' : ActorMethod<[UpdateWorkerInput], [] | [Worker]>,
  'upsertNotificationTemplate' : ActorMethod<[UpsertTemplateInput], TemplateId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];