/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimerRecordView {
    totalPausedNanos: bigint;
    pausedAt?: Timestamp;
    startedAt: Timestamp;
    jobId: JobId;
    state: TimerState;
    elapsedSeconds: bigint;
}
export interface JobStatusEntry {
    status: JobStatus;
    changedBy: Principal;
    note: string;
    timestamp: Timestamp;
}
export type Timestamp = bigint;
export interface CreateWorkerInput {
    name: string;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
}
export interface CreateJobInput {
    customerName: string;
    complexity: JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    projectPrice: bigint;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
}
export type AuditEntryId = bigint;
export interface AttendanceFilter {
    workerId?: WorkerId;
    isLate?: boolean;
    toDate?: string;
    fromDate?: string;
    isAbsent?: boolean;
}
export type TemplateId = bigint;
export interface IncentiveLedgerEntry {
    workerId: WorkerId;
    jobId: JobId;
    distributedAt: Timestamp;
    earlyBonus: boolean;
    amount: bigint;
}
export interface WorkerTimeEntry {
    workerId: WorkerId;
    trackedNanos: bigint;
}
export interface AuditEntry {
    id: AuditEntryId;
    action: string;
    entityId: string;
    timestamp: Timestamp;
    details: string;
    actorPrincipal: Principal;
    entityType: AuditEntityType;
}
export type AttendanceId = bigint;
export interface AssignWorkersInput {
    jobId: JobId;
    assistWorkerIds: Array<WorkerId>;
    primaryWorkerId: WorkerId;
}
export interface NotificationRecord {
    id: NotificationId;
    title: string;
    trigger: NotificationTrigger;
    createdAt: Timestamp;
    entityId?: string;
    message: string;
    recipientRole: RecipientRole;
    readBy: Array<Principal>;
}
export interface Job {
    customerName: string;
    complexity: JobComplexity;
    status: JobStatus;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    cancellationReason?: string;
    projectPrice: bigint;
    createdAt: Timestamp;
    createdBy: Principal;
    jobId: JobId;
    description: string;
    statusHistory: Array<JobStatusEntry>;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
}
export type ImportBatchId = string;
export interface UpdateSettingsInput {
    overdueAlertOffsetHours?: bigint;
    earlyBonusThresholdPercent?: bigint;
    incentivePoolPercent?: bigint;
    absentFlagDays?: bigint;
    idleDetectionMinutes?: bigint;
    lateThresholdMinutes?: bigint;
}
export interface NotificationTemplate {
    id: TemplateId;
    messageTemplate: string;
    active: boolean;
    trigger: NotificationTrigger;
    updatedAt: Timestamp;
    updatedBy: Principal;
    titleTemplate: string;
}
export interface ReassignWorkerInput {
    jobId: JobId;
    toWorkerId: WorkerId;
    fromWorkerId: WorkerId;
    reason: string;
}
export interface Assignment {
    assignedAt: Timestamp;
    assignedBy: Principal;
    reassignmentHistory: Array<ReassignmentEntry>;
    jobId: JobId;
    assistWorkerIds: Array<WorkerId>;
    primaryWorkerId: WorkerId;
}
export interface AuditQueryFilter {
    toTime?: Timestamp;
    entityId?: string;
    fromTime?: Timestamp;
    actorPrincipal?: Principal;
    entityType?: AuditEntityType;
}
export interface AttendanceRecord {
    id: AttendanceId;
    workerId: WorkerId;
    date: string;
    checkOutAt?: Timestamp;
    importedAt: Timestamp;
    isLate: boolean;
    biometricEmployeeId: string;
    checkInAt?: Timestamp;
    importBatchId: ImportBatchId;
    isAbsent: boolean;
}
export interface Worker {
    id: WorkerId;
    status: WorkerStatus;
    name: string;
    createdAt: Timestamp;
    deactivatedAt?: Timestamp;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
}
export interface ImportAttendanceInput {
    records: Array<BiometricRawRecord>;
    batchId: ImportBatchId;
}
export interface UpdateJobInput {
    customerName: string;
    complexity: JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    projectPrice: bigint;
    jobId: JobId;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
}
export interface UpsertTemplateInput {
    messageTemplate: string;
    active: boolean;
    trigger: NotificationTrigger;
    titleTemplate: string;
}
export interface IncentivePoolView {
    status: IncentiveStatus;
    jobId: JobId;
    distributedAt?: Timestamp;
    totalPool: bigint;
    primaryWorkerShare: bigint;
    earlyBonus: bigint;
    assistWorkerShares: Array<AssistShare>;
}
export type JobId = string;
export interface ChangeJobStatusInput {
    note: string;
    jobId: JobId;
    newStatus: JobStatus;
}
export interface ReassignmentEntry {
    changedBy: Principal;
    toWorkerId: WorkerId;
    timestamp: Timestamp;
    fromWorkerId: WorkerId;
    reason: string;
}
export interface UpdateWorkerInput {
    id: WorkerId;
    name: string;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
}
export interface CreateProductInput {
    code?: string;
    name: string;
    notes?: string;
}
export interface BulkUpsertProductInput {
    code?: string;
    name: string;
    notes?: string;
}
export interface CreateNotificationInput {
    title: string;
    trigger: NotificationTrigger;
    entityId?: string;
    message: string;
    recipientRole: RecipientRole;
}
export interface BiometricRawRecord {
    biometricEmployeeId: string;
    event: BiometricEvent;
    eventTimestamp: Timestamp;
}
export interface AttendanceSummary {
    month: string;
    workerId: WorkerId;
    daysAbsent: bigint;
    daysPresent: bigint;
    daysLate: bigint;
}
export type JobComplexity = bigint;
export interface AppSettings {
    overdueAlertOffsetHours: bigint;
    earlyBonusThresholdPercent: bigint;
    incentivePoolPercent: bigint;
    absentFlagDays: bigint;
    idleDetectionMinutes: bigint;
    lateThresholdMinutes: bigint;
}
export type NotificationId = bigint;
export type WorkerId = bigint;
export type ProductId = bigint;
export interface AssistShare {
    workerId: WorkerId;
    amount: bigint;
}
export interface Product {
    id: ProductId;
    active: boolean;
    code?: string;
    name: string;
    notes?: string;
}
export enum AuditEntityType {
    job = "job",
    setting = "setting",
    assignment = "assignment",
    incentive = "incentive",
    notification = "notification",
    attendance = "attendance",
    worker = "worker",
    product = "product"
}
export enum BiometricEvent {
    checkIn = "checkIn",
    checkOut = "checkOut"
}
export enum IncentiveStatus {
    distributed = "distributed",
    pending = "pending"
}
export enum JobPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum JobStatus {
    cancelled = "cancelled",
    completed = "completed",
    pendingAssignment = "pendingAssignment",
    inProgress = "inProgress",
    paused = "paused"
}
export enum NotificationTrigger {
    status_changed = "status_changed",
    worker_idle = "worker_idle",
    attendance_anomaly = "attendance_anomaly",
    job_completed = "job_completed",
    overdue = "overdue",
    job_created = "job_created",
    incentive_awarded = "incentive_awarded"
}
export enum RecipientRole {
    all = "all",
    admin = "admin",
    salesManager = "salesManager",
    workshopManager = "workshopManager"
}
export enum TimerState {
    stopped = "stopped",
    running = "running",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkerStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignWorkers(input: AssignWorkersInput): Promise<Assignment>;
    bulkUpsertProducts(inputs: Array<BulkUpsertProductInput>): Promise<bigint>;
    changeJobStatus(input: ChangeJobStatusInput): Promise<Job | null>;
    createJob(input: CreateJobInput): Promise<Job>;
    createJobIncentivePool(jobId: JobId, projectPrice: bigint, elapsedNanos: bigint, estimatedHours: bigint): Promise<IncentivePoolView | null>;
    createNotification(input: CreateNotificationInput): Promise<NotificationId>;
    createProduct(input: CreateProductInput): Promise<Product>;
    createWorker(input: CreateWorkerInput): Promise<Worker>;
    deactivateProduct(productId: ProductId): Promise<boolean>;
    deactivateWorker(workerId: WorkerId): Promise<boolean>;
    distributeJobIncentive(jobId: JobId, primaryWorker: WorkerId, assistEntries: Array<WorkerTimeEntry>, elapsedNanos: bigint, estimatedHours: bigint): Promise<void>;
    getAllIncentiveLedger(): Promise<Array<IncentiveLedgerEntry>>;
    getAssignment(jobId: JobId): Promise<Assignment | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIdleJobs(): Promise<Array<JobId>>;
    getJob(jobId: JobId): Promise<Job | null>;
    getJobIncentivePool(jobId: JobId): Promise<IncentivePoolView | null>;
    getJobTimerState(jobId: JobId): Promise<TimerRecordView | null>;
    getMonthlyAttendanceSummary(workerId: WorkerId, month: string): Promise<AttendanceSummary>;
    getMyNotifications(role: RecipientRole): Promise<Array<NotificationRecord>>;
    getPendingIncentives(): Promise<Array<IncentivePoolView>>;
    getSettings(): Promise<AppSettings>;
    getTemplateForTrigger(trigger: NotificationTrigger): Promise<NotificationTemplate | null>;
    getUnreadCount(role: RecipientRole): Promise<bigint>;
    getWorker(workerId: WorkerId): Promise<Worker | null>;
    getWorkerLedger(workerId: WorkerId): Promise<Array<IncentiveLedgerEntry>>;
    importAttendance(input: ImportAttendanceInput): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isJobOverdue(jobId: JobId): Promise<boolean | null>;
    listActiveProducts(): Promise<Array<Product>>;
    listAllJobs(): Promise<Array<Job>>;
    listBiometricMappings(): Promise<Array<[string, WorkerId]>>;
    listJobsByStatus(status: JobStatus): Promise<Array<Job>>;
    listJobsByWorker(workerId: WorkerId): Promise<Array<Job>>;
    listNotificationTemplates(): Promise<Array<NotificationTemplate>>;
    listWorkers(status: WorkerStatus | null): Promise<Array<Worker>>;
    markAllNotificationsRead(role: RecipientRole): Promise<void>;
    markNotificationRead(notificationId: NotificationId): Promise<void>;
    pauseJobTimer(jobId: JobId): Promise<TimerRecordView>;
    queryAttendance(filter: AttendanceFilter): Promise<Array<AttendanceRecord>>;
    queryAuditLog(filter: AuditQueryFilter): Promise<Array<AuditEntry>>;
    reassignAssistWorker(input: ReassignWorkerInput): Promise<Assignment | null>;
    reassignPrimaryWorker(input: ReassignWorkerInput): Promise<Assignment | null>;
    resumeJobTimer(jobId: JobId): Promise<TimerRecordView>;
    setBiometricMapping(biometricEmployeeId: string, workerId: WorkerId): Promise<void>;
    setIdleThresholdMinutes(minutes: bigint): Promise<void>;
    setPoolPercent(percent: bigint): Promise<void>;
    startJobTimer(jobId: JobId): Promise<TimerRecordView>;
    stopJobTimer(jobId: JobId): Promise<TimerRecordView>;
    updateJob(input: UpdateJobInput): Promise<Job | null>;
    updateSettings(input: UpdateSettingsInput): Promise<AppSettings>;
    updateWorker(input: UpdateWorkerInput): Promise<Worker | null>;
    upsertNotificationTemplate(input: UpsertTemplateInput): Promise<TemplateId>;
}
import type { Assignment as _Assignment, AssistShare as _AssistShare, AttendanceFilter as _AttendanceFilter, AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AuditEntityType as _AuditEntityType, AuditEntry as _AuditEntry, AuditEntryId as _AuditEntryId, AuditQueryFilter as _AuditQueryFilter, BiometricEvent as _BiometricEvent, BiometricRawRecord as _BiometricRawRecord, BulkUpsertProductInput as _BulkUpsertProductInput, ChangeJobStatusInput as _ChangeJobStatusInput, CreateJobInput as _CreateJobInput, CreateNotificationInput as _CreateNotificationInput, CreateProductInput as _CreateProductInput, CreateWorkerInput as _CreateWorkerInput, ImportAttendanceInput as _ImportAttendanceInput, ImportBatchId as _ImportBatchId, IncentivePoolView as _IncentivePoolView, IncentiveStatus as _IncentiveStatus, Job as _Job, JobComplexity as _JobComplexity, JobId as _JobId, JobPriority as _JobPriority, JobStatus as _JobStatus, JobStatusEntry as _JobStatusEntry, NotificationId as _NotificationId, NotificationRecord as _NotificationRecord, NotificationTemplate as _NotificationTemplate, NotificationTrigger as _NotificationTrigger, Product as _Product, ProductId as _ProductId, RecipientRole as _RecipientRole, TemplateId as _TemplateId, TimerRecordView as _TimerRecordView, TimerState as _TimerState, Timestamp as _Timestamp, UpdateJobInput as _UpdateJobInput, UpdateSettingsInput as _UpdateSettingsInput, UpdateWorkerInput as _UpdateWorkerInput, UpsertTemplateInput as _UpsertTemplateInput, UserRole as _UserRole, Worker as _Worker, WorkerId as _WorkerId, WorkerStatus as _WorkerStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignWorkers(arg0: AssignWorkersInput): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.assignWorkers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignWorkers(arg0);
            return result;
        }
    }
    async bulkUpsertProducts(arg0: Array<BulkUpsertProductInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertProducts(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertProducts(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async changeJobStatus(arg0: ChangeJobStatusInput): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.changeJobStatus(to_candid_ChangeJobStatusInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeJobStatus(to_candid_ChangeJobStatusInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJob(arg0: CreateJobInput): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJobIncentivePool(arg0: JobId, arg1: bigint, arg2: bigint, arg3: bigint): Promise<IncentivePoolView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobIncentivePool(arg0, arg1, arg2, arg3);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobIncentivePool(arg0, arg1, arg2, arg3);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: CreateNotificationInput): Promise<NotificationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProduct(arg0: CreateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_CreateProductInput_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_CreateProductInput_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWorker(arg0: CreateWorkerInput): Promise<Worker> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorker(to_candid_CreateWorkerInput_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Worker_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorker(to_candid_CreateWorkerInput_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Worker_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateProduct(arg0);
            return result;
        }
    }
    async deactivateWorker(arg0: WorkerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateWorker(arg0);
            return result;
        }
    }
    async distributeJobIncentive(arg0: JobId, arg1: WorkerId, arg2: Array<WorkerTimeEntry>, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeJobIncentive(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeJobIncentive(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllIncentiveLedger(): Promise<Array<IncentiveLedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncentiveLedger();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncentiveLedger();
            return result;
        }
    }
    async getAssignment(arg0: JobId): Promise<Assignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignment(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignment(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdleJobs(): Promise<Array<JobId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdleJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdleJobs();
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobIncentivePool(arg0: JobId): Promise<IncentivePoolView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobIncentivePool(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobIncentivePool(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobTimerState(arg0: JobId): Promise<TimerRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobTimerState(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobTimerState(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyAttendanceSummary(arg0: WorkerId, arg1: string): Promise<AttendanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyAttendanceSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyAttendanceSummary(arg0, arg1);
            return result;
        }
    }
    async getMyNotifications(arg0: RecipientRole): Promise<Array<NotificationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingIncentives(): Promise<Array<IncentivePoolView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingIncentives();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingIncentives();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTemplateForTrigger(arg0: NotificationTrigger): Promise<NotificationTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplateForTrigger(to_candid_NotificationTrigger_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplateForTrigger(to_candid_NotificationTrigger_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(arg0: RecipientRole): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getWorker(arg0: WorkerId): Promise<Worker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorker(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorker(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerLedger(arg0: WorkerId): Promise<Array<IncentiveLedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerLedger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerLedger(arg0);
            return result;
        }
    }
    async importAttendance(arg0: ImportAttendanceInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importAttendance(to_candid_ImportAttendanceInput_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importAttendance(to_candid_ImportAttendanceInput_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isJobOverdue(arg0: JobId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.isJobOverdue(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isJobOverdue(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveProducts();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveProducts();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllJobs();
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllJobs();
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBiometricMappings(): Promise<Array<[string, WorkerId]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBiometricMappings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBiometricMappings();
            return result;
        }
    }
    async listJobsByStatus(arg0: JobStatus): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobsByStatus(to_candid_JobStatus_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobsByStatus(to_candid_JobStatus_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobsByWorker(arg0: WorkerId): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobsByWorker(arg0);
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobsByWorker(arg0);
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotificationTemplates(): Promise<Array<NotificationTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotificationTemplates();
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotificationTemplates();
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWorkers(arg0: WorkerStatus | null): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkers(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkers(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(arg0: RecipientRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead(to_candid_RecipientRole_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async pauseJobTimer(arg0: JobId): Promise<TimerRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseJobTimer(arg0);
                return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseJobTimer(arg0);
            return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryAttendance(arg0: AttendanceFilter): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAttendance(to_candid_AttendanceFilter_n81(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAttendance(to_candid_AttendanceFilter_n81(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryAuditLog(arg0: AuditQueryFilter): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAuditLog(to_candid_AuditQueryFilter_n86(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAuditLog(to_candid_AuditQueryFilter_n86(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async reassignAssistWorker(arg0: ReassignWorkerInput): Promise<Assignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reassignAssistWorker(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reassignAssistWorker(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async reassignPrimaryWorker(arg0: ReassignWorkerInput): Promise<Assignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reassignPrimaryWorker(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reassignPrimaryWorker(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async resumeJobTimer(arg0: JobId): Promise<TimerRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeJobTimer(arg0);
                return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeJobTimer(arg0);
            return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBiometricMapping(arg0: string, arg1: WorkerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBiometricMapping(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBiometricMapping(arg0, arg1);
            return result;
        }
    }
    async setIdleThresholdMinutes(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setIdleThresholdMinutes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setIdleThresholdMinutes(arg0);
            return result;
        }
    }
    async setPoolPercent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPoolPercent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPoolPercent(arg0);
            return result;
        }
    }
    async startJobTimer(arg0: JobId): Promise<TimerRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.startJobTimer(arg0);
                return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startJobTimer(arg0);
            return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async stopJobTimer(arg0: JobId): Promise<TimerRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.stopJobTimer(arg0);
                return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopJobTimer(arg0);
            return from_candid_TimerRecordView_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJob(arg0: UpdateJobInput): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_UpdateJobInput_n95(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_UpdateJobInput_n95(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: UpdateSettingsInput): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_UpdateSettingsInput_n97(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_UpdateSettingsInput_n97(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWorker(arg0: UpdateWorkerInput): Promise<Worker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorker(to_candid_UpdateWorkerInput_n99(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorker(to_candid_UpdateWorkerInput_n99(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertNotificationTemplate(arg0: UpsertTemplateInput): Promise<TemplateId> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertNotificationTemplate(to_candid_UpsertTemplateInput_n101(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertNotificationTemplate(to_candid_UpsertTemplateInput_n101(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n85(_uploadFile, _downloadFile, value);
}
function from_candid_AuditEntityType_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntityType): AuditEntityType {
    return from_candid_variant_n94(_uploadFile, _downloadFile, value);
}
function from_candid_AuditEntry_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntry): AuditEntry {
    return from_candid_record_n92(_uploadFile, _downloadFile, value);
}
function from_candid_IncentivePoolView_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncentivePoolView): IncentivePoolView {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_IncentiveStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncentiveStatus): IncentiveStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_JobPriority_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPriority): JobPriority {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatusEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatusEntry): JobStatusEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationRecord_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationRecord): NotificationRecord {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationTemplate_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationTemplate): NotificationTemplate {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationTrigger_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationTrigger): NotificationTrigger {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_RecipientRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipientRole): RecipientRole {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_TimerRecordView_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimerRecordView): TimerRecordView {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TimerState_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimerState): TimerState {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerStatus): WorkerStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Worker_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Worker): Worker {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncentivePoolView]): IncentivePoolView | null {
    return value.length === 0 ? null : from_candid_IncentivePoolView_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Assignment]): Assignment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimerRecordView]): TimerRecordView | null {
    return value.length === 0 ? null : from_candid_TimerRecordView_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationTemplate]): NotificationTemplate | null {
    return value.length === 0 ? null : from_candid_NotificationTemplate_n63(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Worker]): Worker | null {
    return value.length === 0 ? null : from_candid_Worker_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    complexity: _JobComplexity;
    status: _JobStatus;
    carModel: string;
    customerPhone: string;
    productIds: Array<_ProductId>;
    cancellationReason: [] | [string];
    projectPrice: bigint;
    createdAt: _Timestamp;
    createdBy: Principal;
    jobId: _JobId;
    description: string;
    statusHistory: Array<_JobStatusEntry>;
    estimatedHours: bigint;
    carMake: string;
    priority: _JobPriority;
    carYear: bigint;
    carPlate: string;
}): {
    customerName: string;
    complexity: JobComplexity;
    status: JobStatus;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    cancellationReason?: string;
    projectPrice: bigint;
    createdAt: Timestamp;
    createdBy: Principal;
    jobId: JobId;
    description: string;
    statusHistory: Array<JobStatusEntry>;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
} {
    return {
        customerName: value.customerName,
        complexity: value.complexity,
        status: from_candid_JobStatus_n13(_uploadFile, _downloadFile, value.status),
        carModel: value.carModel,
        customerPhone: value.customerPhone,
        productIds: value.productIds,
        cancellationReason: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.cancellationReason)),
        projectPrice: value.projectPrice,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        jobId: value.jobId,
        description: value.description,
        statusHistory: from_candid_vec_n16(_uploadFile, _downloadFile, value.statusHistory),
        estimatedHours: value.estimatedHours,
        carMake: value.carMake,
        priority: from_candid_JobPriority_n19(_uploadFile, _downloadFile, value.priority),
        carYear: value.carYear,
        carPlate: value.carPlate
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    changedBy: Principal;
    note: string;
    timestamp: _Timestamp;
}): {
    status: JobStatus;
    changedBy: Principal;
    note: string;
    timestamp: Timestamp;
} {
    return {
        status: from_candid_JobStatus_n13(_uploadFile, _downloadFile, value.status),
        changedBy: value.changedBy,
        note: value.note,
        timestamp: value.timestamp
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _IncentiveStatus;
    jobId: _JobId;
    distributedAt: [] | [_Timestamp];
    totalPool: bigint;
    primaryWorkerShare: bigint;
    earlyBonus: bigint;
    assistWorkerShares: Array<_AssistShare>;
}): {
    status: IncentiveStatus;
    jobId: JobId;
    distributedAt?: Timestamp;
    totalPool: bigint;
    primaryWorkerShare: bigint;
    earlyBonus: bigint;
    assistWorkerShares: Array<AssistShare>;
} {
    return {
        status: from_candid_IncentiveStatus_n28(_uploadFile, _downloadFile, value.status),
        jobId: value.jobId,
        distributedAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.distributedAt)),
        totalPool: value.totalPool,
        primaryWorkerShare: value.primaryWorkerShare,
        earlyBonus: value.earlyBonus,
        assistWorkerShares: value.assistWorkerShares
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    active: boolean;
    code: [] | [string];
    name: string;
    notes: [] | [string];
}): {
    id: ProductId;
    active: boolean;
    code?: string;
    name: string;
    notes?: string;
} {
    return {
        id: value.id,
        active: value.active,
        code: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.code)),
        name: value.name,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkerId;
    status: _WorkerStatus;
    name: string;
    createdAt: _Timestamp;
    deactivatedAt: [] | [_Timestamp];
    email: string;
    biometricEmployeeId: [] | [string];
    phone: string;
}): {
    id: WorkerId;
    status: WorkerStatus;
    name: string;
    createdAt: Timestamp;
    deactivatedAt?: Timestamp;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_WorkerStatus_n44(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        deactivatedAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.deactivatedAt)),
        email: value.email,
        biometricEmployeeId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.biometricEmployeeId)),
        phone: value.phone
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPausedNanos: bigint;
    pausedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    jobId: _JobId;
    state: _TimerState;
    elapsedSeconds: bigint;
}): {
    totalPausedNanos: bigint;
    pausedAt?: Timestamp;
    startedAt: Timestamp;
    jobId: JobId;
    state: TimerState;
    elapsedSeconds: bigint;
} {
    return {
        totalPausedNanos: value.totalPausedNanos,
        pausedAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.pausedAt)),
        startedAt: value.startedAt,
        jobId: value.jobId,
        state: from_candid_TimerState_n52(_uploadFile, _downloadFile, value.state),
        elapsedSeconds: value.elapsedSeconds
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    trigger: _NotificationTrigger;
    createdAt: _Timestamp;
    entityId: [] | [string];
    message: string;
    recipientRole: _RecipientRole;
    readBy: Array<Principal>;
}): {
    id: NotificationId;
    title: string;
    trigger: NotificationTrigger;
    createdAt: Timestamp;
    entityId?: string;
    message: string;
    recipientRole: RecipientRole;
    readBy: Array<Principal>;
} {
    return {
        id: value.id,
        title: value.title,
        trigger: from_candid_NotificationTrigger_n57(_uploadFile, _downloadFile, value.trigger),
        createdAt: value.createdAt,
        entityId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.entityId)),
        message: value.message,
        recipientRole: from_candid_RecipientRole_n59(_uploadFile, _downloadFile, value.recipientRole),
        readBy: value.readBy
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TemplateId;
    messageTemplate: string;
    active: boolean;
    trigger: _NotificationTrigger;
    updatedAt: _Timestamp;
    updatedBy: Principal;
    titleTemplate: string;
}): {
    id: TemplateId;
    messageTemplate: string;
    active: boolean;
    trigger: NotificationTrigger;
    updatedAt: Timestamp;
    updatedBy: Principal;
    titleTemplate: string;
} {
    return {
        id: value.id,
        messageTemplate: value.messageTemplate,
        active: value.active,
        trigger: from_candid_NotificationTrigger_n57(_uploadFile, _downloadFile, value.trigger),
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy,
        titleTemplate: value.titleTemplate
    };
}
function from_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    workerId: _WorkerId;
    date: string;
    checkOutAt: [] | [_Timestamp];
    importedAt: _Timestamp;
    isLate: boolean;
    biometricEmployeeId: string;
    checkInAt: [] | [_Timestamp];
    importBatchId: _ImportBatchId;
    isAbsent: boolean;
}): {
    id: AttendanceId;
    workerId: WorkerId;
    date: string;
    checkOutAt?: Timestamp;
    importedAt: Timestamp;
    isLate: boolean;
    biometricEmployeeId: string;
    checkInAt?: Timestamp;
    importBatchId: ImportBatchId;
    isAbsent: boolean;
} {
    return {
        id: value.id,
        workerId: value.workerId,
        date: value.date,
        checkOutAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.checkOutAt)),
        importedAt: value.importedAt,
        isLate: value.isLate,
        biometricEmployeeId: value.biometricEmployeeId,
        checkInAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.checkInAt)),
        importBatchId: value.importBatchId,
        isAbsent: value.isAbsent
    };
}
function from_candid_record_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditEntryId;
    action: string;
    entityId: string;
    timestamp: _Timestamp;
    details: string;
    actorPrincipal: Principal;
    entityType: _AuditEntityType;
}): {
    id: AuditEntryId;
    action: string;
    entityId: string;
    timestamp: Timestamp;
    details: string;
    actorPrincipal: Principal;
    entityType: AuditEntityType;
} {
    return {
        id: value.id,
        action: value.action,
        entityId: value.entityId,
        timestamp: value.timestamp,
        details: value.details,
        actorPrincipal: value.actorPrincipal,
        entityType: from_candid_AuditEntityType_n93(_uploadFile, _downloadFile, value.entityType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    pendingAssignment: null;
} | {
    inProgress: null;
} | {
    paused: null;
}): JobStatus {
    return "cancelled" in value ? JobStatus.cancelled : "completed" in value ? JobStatus.completed : "pendingAssignment" in value ? JobStatus.pendingAssignment : "inProgress" in value ? JobStatus.inProgress : "paused" in value ? JobStatus.paused : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): JobPriority {
    return "low" in value ? JobPriority.low : "high" in value ? JobPriority.high : "medium" in value ? JobPriority.medium : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distributed: null;
} | {
    pending: null;
}): IncentiveStatus {
    return "distributed" in value ? IncentiveStatus.distributed : "pending" in value ? IncentiveStatus.pending : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): WorkerStatus {
    return "active" in value ? WorkerStatus.active : "inactive" in value ? WorkerStatus.inactive : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stopped: null;
} | {
    running: null;
} | {
    paused: null;
}): TimerState {
    return "stopped" in value ? TimerState.stopped : "running" in value ? TimerState.running : "paused" in value ? TimerState.paused : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status_changed: null;
} | {
    worker_idle: null;
} | {
    attendance_anomaly: null;
} | {
    job_completed: null;
} | {
    overdue: null;
} | {
    job_created: null;
} | {
    incentive_awarded: null;
}): NotificationTrigger {
    return "status_changed" in value ? NotificationTrigger.status_changed : "worker_idle" in value ? NotificationTrigger.worker_idle : "attendance_anomaly" in value ? NotificationTrigger.attendance_anomaly : "job_completed" in value ? NotificationTrigger.job_completed : "overdue" in value ? NotificationTrigger.overdue : "job_created" in value ? NotificationTrigger.job_created : "incentive_awarded" in value ? NotificationTrigger.incentive_awarded : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    admin: null;
} | {
    salesManager: null;
} | {
    workshopManager: null;
}): RecipientRole {
    return "all" in value ? RecipientRole.all : "admin" in value ? RecipientRole.admin : "salesManager" in value ? RecipientRole.salesManager : "workshopManager" in value ? RecipientRole.workshopManager : value;
}
function from_candid_variant_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    job: null;
} | {
    setting: null;
} | {
    assignment: null;
} | {
    incentive: null;
} | {
    notification: null;
} | {
    attendance: null;
} | {
    worker: null;
} | {
    product: null;
}): AuditEntityType {
    return "job" in value ? AuditEntityType.job : "setting" in value ? AuditEntityType.setting : "assignment" in value ? AuditEntityType.assignment : "incentive" in value ? AuditEntityType.incentive : "notification" in value ? AuditEntityType.notification : "attendance" in value ? AuditEntityType.attendance : "worker" in value ? AuditEntityType.worker : "product" in value ? AuditEntityType.product : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobStatusEntry>): Array<JobStatusEntry> {
    return value.map((x)=>from_candid_JobStatusEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationRecord>): Array<NotificationRecord> {
    return value.map((x)=>from_candid_NotificationRecord_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncentivePoolView>): Array<IncentivePoolView> {
    return value.map((x)=>from_candid_IncentivePoolView_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationTemplate>): Array<NotificationTemplate> {
    return value.map((x)=>from_candid_NotificationTemplate_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Worker>): Array<Worker> {
    return value.map((x)=>from_candid_Worker_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n84(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEntry>): Array<AuditEntry> {
    return value.map((x)=>from_candid_AuditEntry_n91(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceFilter_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceFilter): _AttendanceFilter {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_AuditEntityType_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditEntityType): _AuditEntityType {
    return to_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function to_candid_AuditQueryFilter_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditQueryFilter): _AuditQueryFilter {
    return to_candid_record_n87(_uploadFile, _downloadFile, value);
}
function to_candid_BiometricEvent_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiometricEvent): _BiometricEvent {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_BiometricRawRecord_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiometricRawRecord): _BiometricRawRecord {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_BulkUpsertProductInput_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkUpsertProductInput): _BulkUpsertProductInput {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ChangeJobStatusInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChangeJobStatusInput): _ChangeJobStatusInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJobInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobInput): _CreateJobInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNotificationInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNotificationInput): _CreateNotificationInput {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductInput_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductInput): _CreateProductInput {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CreateWorkerInput_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateWorkerInput): _CreateWorkerInput {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ImportAttendanceInput_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportAttendanceInput): _ImportAttendanceInput {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_JobPriority_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPriority): _JobPriority {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationTrigger_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationTrigger): _NotificationTrigger {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_RecipientRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientRole): _RecipientRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobInput_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobInput): _UpdateJobInput {
    return to_candid_record_n96(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSettingsInput_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSettingsInput): _UpdateSettingsInput {
    return to_candid_record_n98(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateWorkerInput_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateWorkerInput): _UpdateWorkerInput {
    return to_candid_record_n100(_uploadFile, _downloadFile, value);
}
function to_candid_UpsertTemplateInput_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpsertTemplateInput): _UpsertTemplateInput {
    return to_candid_record_n102(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkerStatus_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerStatus): _WorkerStatus {
    return to_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerStatus | null): [] | [_WorkerStatus] {
    return value === null ? candid_none() : candid_some(to_candid_WorkerStatus_n78(_uploadFile, _downloadFile, value));
}
function to_candid_record_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: WorkerId;
    name: string;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
}): {
    id: _WorkerId;
    name: string;
    email: string;
    biometricEmployeeId: [] | [string];
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        biometricEmployeeId: value.biometricEmployeeId ? candid_some(value.biometricEmployeeId) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageTemplate: string;
    active: boolean;
    trigger: NotificationTrigger;
    titleTemplate: string;
}): {
    messageTemplate: string;
    active: boolean;
    trigger: _NotificationTrigger;
    titleTemplate: string;
} {
    return {
        messageTemplate: value.messageTemplate,
        active: value.active,
        trigger: to_candid_NotificationTrigger_n33(_uploadFile, _downloadFile, value.trigger),
        titleTemplate: value.titleTemplate
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    complexity: JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    projectPrice: bigint;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
}): {
    customerName: string;
    complexity: _JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<_ProductId>;
    projectPrice: bigint;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: _JobPriority;
    carYear: bigint;
    carPlate: string;
} {
    return {
        customerName: value.customerName,
        complexity: value.complexity,
        carModel: value.carModel,
        customerPhone: value.customerPhone,
        productIds: value.productIds,
        projectPrice: value.projectPrice,
        description: value.description,
        estimatedHours: value.estimatedHours,
        carMake: value.carMake,
        priority: to_candid_JobPriority_n23(_uploadFile, _downloadFile, value.priority),
        carYear: value.carYear,
        carPlate: value.carPlate
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    trigger: NotificationTrigger;
    entityId?: string;
    message: string;
    recipientRole: RecipientRole;
}): {
    title: string;
    trigger: _NotificationTrigger;
    entityId: [] | [string];
    message: string;
    recipientRole: _RecipientRole;
} {
    return {
        title: value.title,
        trigger: to_candid_NotificationTrigger_n33(_uploadFile, _downloadFile, value.trigger),
        entityId: value.entityId ? candid_some(value.entityId) : candid_none(),
        message: value.message,
        recipientRole: to_candid_RecipientRole_n35(_uploadFile, _downloadFile, value.recipientRole)
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    biometricEmployeeId?: string;
    phone: string;
}): {
    name: string;
    email: string;
    biometricEmployeeId: [] | [string];
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        biometricEmployeeId: value.biometricEmployeeId ? candid_some(value.biometricEmployeeId) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code?: string;
    name: string;
    notes?: string;
}): {
    code: [] | [string];
    name: string;
    notes: [] | [string];
} {
    return {
        code: value.code ? candid_some(value.code) : candid_none(),
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    records: Array<BiometricRawRecord>;
    batchId: ImportBatchId;
}): {
    records: Array<_BiometricRawRecord>;
    batchId: _ImportBatchId;
} {
    return {
        records: to_candid_vec_n68(_uploadFile, _downloadFile, value.records),
        batchId: value.batchId
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note: string;
    jobId: JobId;
    newStatus: JobStatus;
}): {
    note: string;
    jobId: _JobId;
    newStatus: _JobStatus;
} {
    return {
        note: value.note,
        jobId: value.jobId,
        newStatus: to_candid_JobStatus_n8(_uploadFile, _downloadFile, value.newStatus)
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biometricEmployeeId: string;
    event: BiometricEvent;
    eventTimestamp: Timestamp;
}): {
    biometricEmployeeId: string;
    event: _BiometricEvent;
    eventTimestamp: _Timestamp;
} {
    return {
        biometricEmployeeId: value.biometricEmployeeId,
        event: to_candid_BiometricEvent_n71(_uploadFile, _downloadFile, value.event),
        eventTimestamp: value.eventTimestamp
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId?: WorkerId;
    isLate?: boolean;
    toDate?: string;
    fromDate?: string;
    isAbsent?: boolean;
}): {
    workerId: [] | [_WorkerId];
    isLate: [] | [boolean];
    toDate: [] | [string];
    fromDate: [] | [string];
    isAbsent: [] | [boolean];
} {
    return {
        workerId: value.workerId ? candid_some(value.workerId) : candid_none(),
        isLate: value.isLate ? candid_some(value.isLate) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        isAbsent: value.isAbsent ? candid_some(value.isAbsent) : candid_none()
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toTime?: Timestamp;
    entityId?: string;
    fromTime?: Timestamp;
    actorPrincipal?: Principal;
    entityType?: AuditEntityType;
}): {
    toTime: [] | [_Timestamp];
    entityId: [] | [string];
    fromTime: [] | [_Timestamp];
    actorPrincipal: [] | [Principal];
    entityType: [] | [_AuditEntityType];
} {
    return {
        toTime: value.toTime ? candid_some(value.toTime) : candid_none(),
        entityId: value.entityId ? candid_some(value.entityId) : candid_none(),
        fromTime: value.fromTime ? candid_some(value.fromTime) : candid_none(),
        actorPrincipal: value.actorPrincipal ? candid_some(value.actorPrincipal) : candid_none(),
        entityType: value.entityType ? candid_some(to_candid_AuditEntityType_n88(_uploadFile, _downloadFile, value.entityType)) : candid_none()
    };
}
function to_candid_record_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    complexity: JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<ProductId>;
    projectPrice: bigint;
    jobId: JobId;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: JobPriority;
    carYear: bigint;
    carPlate: string;
}): {
    customerName: string;
    complexity: _JobComplexity;
    carModel: string;
    customerPhone: string;
    productIds: Array<_ProductId>;
    projectPrice: bigint;
    jobId: _JobId;
    description: string;
    estimatedHours: bigint;
    carMake: string;
    priority: _JobPriority;
    carYear: bigint;
    carPlate: string;
} {
    return {
        customerName: value.customerName,
        complexity: value.complexity,
        carModel: value.carModel,
        customerPhone: value.customerPhone,
        productIds: value.productIds,
        projectPrice: value.projectPrice,
        jobId: value.jobId,
        description: value.description,
        estimatedHours: value.estimatedHours,
        carMake: value.carMake,
        priority: to_candid_JobPriority_n23(_uploadFile, _downloadFile, value.priority),
        carYear: value.carYear,
        carPlate: value.carPlate
    };
}
function to_candid_record_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overdueAlertOffsetHours?: bigint;
    earlyBonusThresholdPercent?: bigint;
    incentivePoolPercent?: bigint;
    absentFlagDays?: bigint;
    idleDetectionMinutes?: bigint;
    lateThresholdMinutes?: bigint;
}): {
    overdueAlertOffsetHours: [] | [bigint];
    earlyBonusThresholdPercent: [] | [bigint];
    incentivePoolPercent: [] | [bigint];
    absentFlagDays: [] | [bigint];
    idleDetectionMinutes: [] | [bigint];
    lateThresholdMinutes: [] | [bigint];
} {
    return {
        overdueAlertOffsetHours: value.overdueAlertOffsetHours ? candid_some(value.overdueAlertOffsetHours) : candid_none(),
        earlyBonusThresholdPercent: value.earlyBonusThresholdPercent ? candid_some(value.earlyBonusThresholdPercent) : candid_none(),
        incentivePoolPercent: value.incentivePoolPercent ? candid_some(value.incentivePoolPercent) : candid_none(),
        absentFlagDays: value.absentFlagDays ? candid_some(value.absentFlagDays) : candid_none(),
        idleDetectionMinutes: value.idleDetectionMinutes ? candid_some(value.idleDetectionMinutes) : candid_none(),
        lateThresholdMinutes: value.lateThresholdMinutes ? candid_some(value.lateThresholdMinutes) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == JobPriority.low ? {
        low: null
    } : value == JobPriority.high ? {
        high: null
    } : value == JobPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationTrigger): {
    status_changed: null;
} | {
    worker_idle: null;
} | {
    attendance_anomaly: null;
} | {
    job_completed: null;
} | {
    overdue: null;
} | {
    job_created: null;
} | {
    incentive_awarded: null;
} {
    return value == NotificationTrigger.status_changed ? {
        status_changed: null
    } : value == NotificationTrigger.worker_idle ? {
        worker_idle: null
    } : value == NotificationTrigger.attendance_anomaly ? {
        attendance_anomaly: null
    } : value == NotificationTrigger.job_completed ? {
        job_completed: null
    } : value == NotificationTrigger.overdue ? {
        overdue: null
    } : value == NotificationTrigger.job_created ? {
        job_created: null
    } : value == NotificationTrigger.incentive_awarded ? {
        incentive_awarded: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientRole): {
    all: null;
} | {
    admin: null;
} | {
    salesManager: null;
} | {
    workshopManager: null;
} {
    return value == RecipientRole.all ? {
        all: null
    } : value == RecipientRole.admin ? {
        admin: null
    } : value == RecipientRole.salesManager ? {
        salesManager: null
    } : value == RecipientRole.workshopManager ? {
        workshopManager: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiometricEvent): {
    checkIn: null;
} | {
    checkOut: null;
} {
    return value == BiometricEvent.checkIn ? {
        checkIn: null
    } : value == BiometricEvent.checkOut ? {
        checkOut: null
    } : value;
}
function to_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == WorkerStatus.active ? {
        active: null
    } : value == WorkerStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditEntityType): {
    job: null;
} | {
    setting: null;
} | {
    assignment: null;
} | {
    incentive: null;
} | {
    notification: null;
} | {
    attendance: null;
} | {
    worker: null;
} | {
    product: null;
} {
    return value == AuditEntityType.job ? {
        job: null
    } : value == AuditEntityType.setting ? {
        setting: null
    } : value == AuditEntityType.assignment ? {
        assignment: null
    } : value == AuditEntityType.incentive ? {
        incentive: null
    } : value == AuditEntityType.notification ? {
        notification: null
    } : value == AuditEntityType.attendance ? {
        attendance: null
    } : value == AuditEntityType.worker ? {
        worker: null
    } : value == AuditEntityType.product ? {
        product: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    cancelled: null;
} | {
    completed: null;
} | {
    pendingAssignment: null;
} | {
    inProgress: null;
} | {
    paused: null;
} {
    return value == JobStatus.cancelled ? {
        cancelled: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value == JobStatus.pendingAssignment ? {
        pendingAssignment: null
    } : value == JobStatus.inProgress ? {
        inProgress: null
    } : value == JobStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BulkUpsertProductInput>): Array<_BulkUpsertProductInput> {
    return value.map((x)=>to_candid_BulkUpsertProductInput_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BiometricRawRecord>): Array<_BiometricRawRecord> {
    return value.map((x)=>to_candid_BiometricRawRecord_n69(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
